### ISSUE TITLE
PyDP crashes when used with large lists

### ISSUE THREAD

**Issue by replomancer** [OpenMined/PyDP#174]
## Description

This program:
```python
import pydp

example_list = [5 for _ in range(1000000000)]
print("The previous instruction did not crash the script.", flush=True)
print(pydp.BoundedMean(1.0, 0, 10).result(example_list))
```
crashes with
```
The previous instruction did not crash the script.
Killed
```
output. It's the same when I replace `BoundedMean` with `BoundedSum` or `Count`. I suspect that most or all algorithms are crashing like this. It works fine when `example_list` is smaller.
 
## How to Reproduce

Running the above code will probably produce same results on other machines. If not, try with a longer list. Actually the list creation can also crash the script for you, but that's still relevant: the library expects a list input (iterable is not enough), so working with more data gets challenging pretty fast.

## Expected Behavior

I would expect PyDP to handle big input or provide API to add data in batches e.g. the C++ library has `AddEntries` method which can be called multiple times before computing result. 
PyDP could expose `AddEntries` or partition input data before calling `AddEntries` in a loop when `result` is called. 

## System Information
 - OS: Ubuntu
 - OS Version: 20.04
 - Language Version: Python 3.8

## Additional Context

Python's limit for a list size is not an issue here. Here's how you can see the list size limit on your system:
```python
>>> import sys
>>> sys.maxsize
9223372036854775807
```
so I'm nowhere near size limits in my example.

**Comment by jeamick** [comment]
hello @replomancer,

I will try to look at it.

JM

**Comment by chinmayshah99** [comment]
hey @replomancer, I'm finding it difficult to replicate. 
I tried doing it on [google collab](https://colab.research.google.com/drive/1M2p45QpG_wrc4a5aTznlBa_4XJAD8_Tz?usp=sharing) and I can't allocate this array itself. 

On my local machine too, I could not load this array. 
I suspect what might have happened is the RAM has almost reached it's limit and thus next operation is killed if sufficient memory is not available ( a standard practices in Linux)

Though what we could do is move data from pybind11 list to vector rather than copy.
To be specific, pop the element from list and insert it into vector.

**Comment by replomancer** [comment]
Main point is there is currently no way to feed more data to PyDP algorithms.

The `result` method expects a list, so you have to build it first (big list may crash your interpreter).
There is no way to use an iterable or add data in batches.

Adding data in batches is the way C++ library handles big data: if your data doesn't fit into memory or a datastructure you just add it piece by piece calling `AddEntries` method multiple times.

I think PyDP could have some counterpart of `AddEntries`.

**Comment by chinmayshah99** [comment]
Yeah, we are thinking of adding the Add entries method real soon! Thanks
for pointing that out.

Regards

Chinmay Shah
