### ISSUE TITLE
Geometric Distribution Ratio tests failing

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#213]
## Description
https://github.com/OpenMined/PyDP/blob/dev/tests/algorithms/test_distributions.py#L107
Running this test for Geometric Distribution ratios generates output which exceeds the +-1 threshold by 0.01-0.03. Need to verify whether this issue is in the data generation process(underlying code). 

## Expected Behavior
The test should pass

**Comment by grilhami** [comment]
I'll be taking on this one

**Comment by grilhami** [comment]
After some investigation it seems there where two issues that made the testing failed:

1. In line 126 of the `test_distribution.py` file, it supposed to be `c_j / c_i` instead of `c_i / c_j`. In the google-dp library they also cast it to `float` type first, but it seems not too necessary seems even without casting it to a `float` results in the same result.
2. It seems that the way the **samples** are being generated by the pydp's `GeometricDistribution` class are quite different with the on in google-dp; this results in a difference in the occurence of each sample from the distribution, which results in values of the ratios. If I try ry to use the counts generated by google-dp in the test script, the test passed. Also, there seems to be a difference in the standard deviation of the ratios between google-dp and pydp. 

I'm just gonna put the ratios here in case anybody's curios.

**Ratios from google-dp**:` [1.009728, 0.990566, 0.981155, 0.997522, 0.97971, 0.975697, 1.019601, 0.973765, 0.998146, 0.992132, 0.97698, 1.005524, 1.004485, 0.968747, 0.974191, 1.002129, 0.972737, 1.006066, 0.976242, 0.998271, 1.010519, 0.981019, 0.998128, 0.974362, 0.996278, 1.003865, 0.987295, 0.978292, 0.984055, 1.003916, 0.965299, 1.026613, 0.981406, 0.977873, 1.00594, 0.98566, 0.977607, 0.986431, 0.967904, 1.027048, 0.997322, 0.997315, 0.99641, 0.960366, 1.010005, 0.984832, 0.998114, 0.959534, 0.990647, 1.005301]`
Mean = `0.990455`
Standard Seviation = `0.016218408667754234`

**Ratios from PyDP:** `[0.9401671799384074, 1.3646856964592107, 1.0117727740313178, 0.9622684139177587, 0.9531580183141583, 0.8030545633698731, 1.2572085889570552, 0.7766255947297792, 1.037071944706252, 1.3760981520751288, 1.0825536598789214, 0.7617691916624301, 1.2497330485851574, 0.9726583360034177, 0.8004831448336445, 1.1945130315500685, 0.8528938906752411, 1.0367577756833177, 0.8935064935064935, 1.4498546511627908, 0.7249122807017544, 0.9279491080071912, 1.3469448584202683, 0.9499889356052224, 0.8386908921500117, 0.9108457158727954, 0.9123341972861717, 1.2526737967914439, 1.3008271077908218, 0.7232078761152703, 0.9783040272263188, 0.9036092187273518, 1.4249278152069298, 0.7563886074524372, 1.4798333085280548, 0.7666700191089209, 1.2178932178932178, 0.9012279190004309, 0.9471734193856819, 1.1973501577287067, 0.6517019707029191, 1.285575679172057, 1.0515723270440251, 0.9240430622009569, 1.0218770226537217, 0.7865467443628072, 0.9959735867289419, 1.3523609314359637, 1.146598110725816, 0.8054020231515278]`
Mean = `1.0252047617443631`
Standard Seviation = `0.2212118580373974`


For number 1, solving it is pretty straight forward. However, I'm still looking into number 2 at the moment.

**Comment by grilhami** [comment]
Found out the issue. It seems that the way `Counter` works, is not the same as how they count the samples in the Google DP test distribution C++ file.

In C++, `Counter` is like `map`, which involves key-value pairs. In the Google DP test fil, they used `vector` which is an array. In their case, an array of all 0s with a length of 51.

When we try to use `Counter` and retrieve all of its values, the order of the counts is ordered by their frequency. While according to the original test file, we have to preserve the index order of the array. 

Creating a PR soon to solve this.
