### ISSUE TITLE
Upgrade default python version to python 3.8 on Linux System

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#432]
## Description
Python 3.6 is deprecated and hence there is no point in installing py36 as a default version. Rather we should be installing python 3.8.
File to be updated: https://github.com/OpenMined/PyDP/blob/dev/prereqs_linux.sh#L26

## Additional Context
Add any other context or screenshots.

**Comment by emmcauley** [comment]
I tracked the origin of this code back to pull request #32 / issue #31. There didn't seem to be a specific reason documented to lock specifically to Python 3.6 or pull in a custom PPA. Rather than install a custom PPA, would it be better to let the Ubuntu/Debian "python3" meta-package select the supported version of Python3 for that system? For example, on Ubuntu 22.04, it would default to Python 3.10, and on 20.04, it defaults to Python3.8. 

This discussion examines some of the considerations when you override the default Python3 package selection (at least on Ubuntu): https://askubuntu.com/questions/1398568/installing-python-who-is-deadsnakes-and-why-should-i-trust-them

I am new to the OpenMined community and I will link a PR (#444) in case you'd like to go in that direction.
