### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#61]
Since the environment setup is very complex, using Docker would be the easiest way to setup. 
This will boost cross-platform development too, especially among our friends using Windows!

**Comment by chinmayshah99** [comment]
@replomancer , can we use docker volume instead of Copying file?

**Comment by replomancer** [comment]
@chinmayshah99 It depends on what we want. If you're thinking of using volumes to have code available for the build then it's not possible. You can only mount volumes when you run a docker container, not when you build an image (there's no such option for build). Whatever we want to be available during the build needs to be copied there, so if we want the image to include PyDP, then we need to copy. It may also make sense to have a more basic Docker image without PyDP and use volumes to build the lib inside after running (? I'm just thinking aloud and it's very late :crescent_moon:). In my setup I actually used volumes a lot already with this Dockerfile, but it works badly for me: for instance when I recently wrote about docstrings still being unavailable after the parentheses fix, I was actually testing the code I had on the host vs what I had in a fresh container because I had a mounted volume :man_facepalming: So docstrings are actually fine now after that recent PR.

**Comment by chinmayshah99** [comment]
Alright, then we should stick with the current configuration.
